FROM openjdk-8u201-jdk-alpine3.9-timezone-bangkok:1.0
LABEL maintainer="Eknarong Aphiphutthikul (eknarong.ap@gmail.com)"
LABEL Description="base image : openjdk:8u201-jdk-alpine3.9 Set timezone Bangkok" Version="1.0"
RUN addgroup -S appgroup \
&& adduser -D appuser -G appgroup \
	&& mkdir /home/appuser/app/ \
	&& mkdir /home/appuser/applog/ \
	&& mkdir /home/appuser/applog/gc/ \
	&& mkdir /home/appuser/appconfig/ \
	&& chown -R appuser:appgroup /home/appuser/app/ \
	&& chown -R appuser:appgroup /home/appuser/applog/ \
	&& chown -R appuser:appgroup /home/appuser/applog/gc/ \
	&& chown -R appuser:appgroup /home/appuser/appconfig/
COPY target/jvm-springboot-setting-1.0.0.jar /home/appuser/app/app.jar
WORKDIR /home/appuser/
ENTRYPOINT java -Dfile.encoding=tis-620 -Dlog4j2.formatMsgNoLookups=true -DKUBERNETES_NAMESPACE=${KUBERNETES_NAMESPACE} -DKUBERNETES_PODNAME=${KUBERNETES_PODNAME}  ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /home/appuser/app/app.jar

